services:
  apache:
    build: ./apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - backend1
      - backend2
  backend1:
    image: 	website-web
    expose:
      - 8280
  backend2:
    image: 	linuxserver/emulatorjs:latest
    expose:
      - 45678
