version: '3.8'

services:
  apache:
    build: ./apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/default.conf:/etc/apache2/sites-available/000-default.conf
    restart: always
